# -*- coding: utf-8 -*-
"""project_112.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gBy3KuGLDOL0k8vB0afRgsVQuGvqLk_-
"""

import csv
import statistics
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
df = pd.read_csv("project_112.csv")

fig = px.scatter(df, y = "quant_saved",color = "female")
fig.show()

with open("project_112.csv",newline="") as f:
  reader = csv.reader(f)
  savings_data = list(reader)

savings_data.pop(0)

total_entries  = len(savings_data)
total_females = 0

for data in savings_data:
  if int(data[3]) == 1:
    total_females += 1

fig = go.Figure(go.Bar(x = ["Female","Male"],y = [total_females,(total_entries - total_females)]))
fig.show()

all_savings = []
for data in savings_data:
  all_savings.append(float(data[0]))


print(f"Mean of savings: {statistics.mean(all_savings)}")  
print(f"Mode of savings: {statistics.mode(all_savings)}")  
print(f"Median of savings: {statistics.median(all_savings)}")

females = []
males = []
for data in savings_data:
  if int(data[3]) == 1:
    females.append(float(data[0]))
  else:
    males.append(float(data[0]))

print("Result for people who are females")
print(f"Mean of savings: {statistics.mean(females)}")  
print(f"Mode of savings: {statistics.mode(females)}")  
print(f"Median of savings: {statistics.median(females)}")

print("\n\n")

print("Result for people who are males")
print(f"Mean of savings: {statistics.mean(males)}")  
print(f"Mode of savings: {statistics.mode(males)}")  
print(f"Median of savings: {statistics.median(males)}")

